const data = {
  event_type:'boda',
  nombre_novia:'Dania',
  nombre_novio:'Alfonso',
  nombre_papa_novia:'Daniel Aguilar Fernandez',
  nombre_mama_novia:'Ma. Guadalupe Chavez Ramos',
  nombre_papa_novio:'Jorge Isaac Miranda Salgado',
  nombre_mama_novio:'Maria Aurora Mendiola Miranda',
  frase:'Quienes estan destinados a ser, Siempre acaban siendo.',
  img_header:'back.webp',
  img_fondo1:'',
  img_fondo2:'',
  fecha_dia:'09',
  fecha_mes:'Noviembre',
  fecha_year:'2024',
  religiosa_hora:'19:00',
  religiosa_lugar:'Iglesia San Francisco de Asís',
  religiosa_direccion:'Bandera Nacional S/N',
  religiosa_direccion_col:'Centro',
  religiosa_direccion_cd:'Iguala de la Independencia',
  religiosa_ubicacion:'https://maps.app.goo.gl/EDvoETidvMd6dmcu6',
  recepcion_hora:'20:00',
  recepcion_lugar:'Rinconada Hotel Boutique',
  recepcion_direccion:'General Baltazar R. Leyva Mancilla, 19',
  recepcion_direccion_col:'Centro',
  recepcion_direccion_cd:'Iguala de la Independencia, Guerrero',
  recepcion_ubicacion:'https://maps.app.goo.gl/81dqrkE91nPJy78K7',
  confirmacion_novia:'7331006444',
  confirmacion_novio:'',
}

export default data